In [1]:
"""
<다중회귀모델(Multiple Regression)>
 - 여러 개의 특성을 사용한 회귀모델을 다중회귀모델이라고 칭합니다.
 - 특성이 많을수록 매우 복잡한(정확도가 높은) 모델을 표현할 수 있음
   (복잡도를 높이는 방법 중의 한가지 입니다.)
 - 다중회귀모델 산술식(독립변수의 특성이 여러 개)
    y = ax1 + bx2 + cx3 + ... + 절편
     --> a, b, c, ..., n : 계수
     --> 마지막 값이 y절편
     --> x값은 독립변수
"""

'\n<다중회귀모델(Multiple Regression)>\n - 여러 개의 특성을 사용한 회귀모델을 다중회귀모델이라고 칭합니다.\n - 특성이 많을수록 매우 복잡한(정확도가 높은) 모델을 표현할 수 있음\n   (복잡도를 높이는 방법 중의 한가지 입니다.)\n - 다중회귀모델 산술식(독립변수의 특성이 여러 개)\n    y = ax1 + bx2 + cx3 + ... + 절편\n     --> a, b, c, ..., n : 계수\n     --> 마지막 값이 y절편\n     --> x값은 독립변수\n'

### 1. 데이터 수집하기

In [2]:
### 구글드라이브에 data 폴더에 03_농어의_길이_높이_두께_데이터.csv 파일 사용
# - 데이터 불러들이기 -> 데이터프레임으로 생성하기
# - 변수명 : df

In [3]:
import pandas as pd
df = pd.read_csv("./data/03_농어의_길이_높이_두께_데이터.csv")
df

length  height  width
0      8.4    2.11   1.41
1     13.7    3.53   2.00
2     15.0    3.82   2.43
3     16.2    4.59   2.63
4     17.4    4.59   2.94
5     18.0    5.22   3.32
6     18.7    5.20   3.12
7     19.0    5.64   3.05
8     19.6    5.14   3.04
9     20.0    5.08   2.77
10    21.0    5.69   3.56
11    21.0    5.92   3.31
12    21.0    5.69   3.67
13    21.3    6.38   3.53
14    22.0    6.11   3.41
15    22.0    5.64   3.52
16    22.0    6.11   3.52
17    22.0    5.88   3.52
18    22.0    5.52   4.00
19    22.5    5.86   3.62
20    22.5    6.79   3.62
21    22.7    5.95   3.63
22    23.0    5.22   3.63
23    23.5    6.28   3.72
24    24.0    7.29   3.72
25    24.0    6.38   3.82
26    24.6    6.73   4.17
27    25.0    6.44   3.68
28    25.6    6.56   4.24
29    26.5    7.17   4.14
30    27.3    8.32   5.14
31    27.5    7.17   4.34
32    27.5    7.05   4.34
33    27.5    7.28   4.57
34    28.0    7.82   4.20
35    28.7    7.59   4.64
36    30.0    7.62   4.77
37    32.8   10.03   6.02
38    34.5   10.26   6.39
39    35.0   11.49   7.80
40    36.5   10.88   6.86
41    36.0   10.61   6.74
42    37.0   10.84   6.26
43    37.0   10.57   6.37
44    39.0   11.14   7.49
45    39.0   11.14   6.00
46    39.0   12.43   7.35
47    40.0   11.93   7.11
48    40.0   11.73   7.22
49    40.0   12.38   7.46
50    40.0   11.14   6.63
51    42.0   12.80   6.87
52    43.0   11.93   7.28
53    43.0   12.51   7.42
54    43.5   12.60   8.14
55    44.0   12.49   7.60

In [4]:
### 길이, 높이, 두께 데이터를 이용해서 무게 예측하기

In [5]:
### 데이터프레임의 데이터형태를 numpy의 array 배열 형태로 변환하기
### 독립변수로 사용..
perch_full = df.to_numpy()
perch_full.shape

(56, 3)

In [6]:
perch_full

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [7]:
import numpy as np

### 농어 무게(종속변수)
perch_weight = np.array(
                                [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
                                 110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
                                 130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
                                 197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
                                 514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
                                 820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
                                 1000.0, 1000.0]
                                 )
perch_weight.shape

(56,)

In [8]:
### 훈련데이터, 테스트데이터 분류하기
# - 분류 기준은 70 : 30으로 합니다.
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state=42, test_size=0.3)
print(train_input.shape, train_target.shape)
print(test_input.shape, test_target.shape)

(39, 3) (39,)
(17, 3) (17,)


### 특성공학 적용하기 : 특성만들기

In [9]:
"""
<특성공학>
 - 복잡도를 높이기 위하여 원본 특성의 조합연산을 통해서 새로운 특성을 생성한다는 의미
 - 원본 특성과 완전히 별개의 특성이 아니며,
 - 원본 특성의 조합연산으로 만들어집니다.
 - 사이킷런의 라이브러리를 이용하게 되며,
 - 이 때 사용하는 라이브러리 이름을 "변환기"라고 칭합니다.
 
<특성 생성 라이브러리>
 - 사용 패키지 : sklearn.preprocessing
 - 사용 클래스 : PolynomialFeatures(변환기)
 - 사용 함수 : fit, transform, fit_transform
   (변환 순서)
    fit > transform (or fit_transform)
 - 사용 데이터 : 훈련 및 테스트의 독립변수
 - 종속변수는 절대로 변환하면 안됨!!!!!!!!!!!!!!!!!!!!!!!!!!!
"""

'\n<특성공학>\n - 복잡도를 높이기 위하여 원본 특성의 조합연산을 통해서 새로운 특성을 생성한다는 의미\n - 원본 특성과 완전히 별개의 특성이 아니며,\n - 원본 특성의 조합연산으로 만들어집니다.\n - 사이킷런의 라이브러리를 이용하게 되며,\n - 이 때 사용하는 라이브러리 이름을 "변환기"라고 칭합니다.\n \n<특성 생성 라이브러리>\n - 사용 패키지 : sklearn.preprocessing\n - 사용 클래스 : PolynomialFeatures(변환기)\n - 사용 함수 : fit, transform, fit_transform\n   (변환 순서)\n    fit > transform (or fit_transform)\n - 사용 데이터 : 훈련 및 테스트의 독립변수\n - 종속변수는 절대로 변환하면 안됨!!!!!!!!!!!!!!!!!!!!!!!!!!!\n'

In [10]:
### 변환기로 사용할 클래스 불러들이기
from sklearn.preprocessing import PolynomialFeatures

In [11]:
### 변환기 클래스 생성하기(전처리 모델)
# - include_bias=False : y절편값은 생성하지 않기
poly = PolynomialFeatures(include_bias=False)
poly

PolynomialFeatures(include_bias=False)

In [12]:
### sample 데이터 사용
temp_data = [[2, 3 , 4]]
temp_data

[[2, 3, 4]]

In [13]:
### 특성의 조합을 찾는 전처리 모델이기 때문에 종속변수는 사용하지 않음
# - 특성의 조합을 찾아내는 과정
poly.fit(temp_data)

PolynomialFeatures(include_bias=False)

In [14]:
### 찾은 특성의 조합으로 변환시키기(특성 생성시킴)
poly.transform(temp_data)

array([[ 2.,  3.,  4.,  4.,  6.,  8.,  9., 12., 16.]])

In [15]:
"""
<변환기 결과 해석>
 - 첫번째 값 1 : y절편값(무조건 변환기는 1을 반환해 줍니다. 추후 사용안함)
 - 두번째 값과 세번째 값 : 독립변수 원본값 그대로 생성
 - 네번째 값 : 두번째 독립변수의 제곱승한 값
 - 다섯번째 값 : 독립변수 2개를 곱한 값
 - 여섯번째 값 :세번째 독립변수의 제곱승한 값
"""

'\n<변환기 결과 해석>\n - 첫번째 값 1 : y절편값(무조건 변환기는 1을 반환해 줍니다. 추후 사용안함)\n - 두번째 값과 세번째 값 : 독립변수 원본값 그대로 생성\n - 네번째 값 : 두번째 독립변수의 제곱승한 값\n - 다섯번째 값 : 독립변수 2개를 곱한 값\n - 여섯번째 값 :세번째 독립변수의 제곱승한 값\n'

In [16]:
### 훈련 및 테스트 독립변수를 이용해서 특성 생성하기
# - 차원은 2차원까지 사용할 예정입니다.
#   (degree = 2, 기본값, 생략가능)
poly = PolynomialFeatures(degree=2, include_bias=False)
poly

PolynomialFeatures(include_bias=False)

In [17]:
### 특성 조합 패턴 찾아내기
# - 패턴을 찾아낼 때는 훈련데이터만 사용합니다.
#    (테스트데이터는 절대 사용하면 안됩니다.)
# - 모든 모델의 기준은 훈련데이터 기준입니다.
poly.fit(train_input)

PolynomialFeatures(include_bias=False)

In [18]:
### 찾은 조합을 이용해서 자동 변환 및 생성시키기
# 훈련데이터 변환하기
train_poly = poly.transform(train_input)

# 테스트데이터 변환하기
test_poly = poly.transform(test_input)

print(train_poly.shape, test_poly.shape)

(39, 9) (17, 9)


In [19]:
train_poly

array([[  17.4   ,    4.59  ,    2.94  ,  302.76  ,   79.866 ,   51.156 ,
          21.0681,   13.4946,    8.6436],
       [  36.    ,   10.61  ,    6.74  , 1296.    ,  381.96  ,  242.64  ,
         112.5721,   71.5114,   45.4276],
       [  25.    ,    6.44  ,    3.68  ,  625.    ,  161.    ,   92.    ,
          41.4736,   23.6992,   13.5424],
       [  40.    ,   11.93  ,    7.11  , 1600.    ,  477.2   ,  284.4   ,
         142.3249,   84.8223,   50.5521],
       [  39.    ,   12.43  ,    7.35  , 1521.    ,  484.77  ,  286.65  ,
         154.5049,   91.3605,   54.0225],
       [  43.    ,   11.93  ,    7.28  , 1849.    ,  512.99  ,  313.04  ,
         142.3249,   86.8504,   52.9984],
       [  22.    ,    5.64  ,    3.52  ,  484.    ,  124.08  ,   77.44  ,
          31.8096,   19.8528,   12.3904],
       [  20.    ,    5.08  ,    2.77  ,  400.    ,  101.6   ,   55.4   ,
          25.8064,   14.0716,    7.6729],
       [  22.    ,    6.11  ,    3.52  ,  484.    ,  134.42  ,   77.44  

In [20]:
### fit()을 통해 찾아낸 특성의 조합 확인하기
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

### 훈련하기

In [21]:
### 훈련모델 생성하기
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr

LinearRegression()

In [22]:
### 훈련시키기
lr.fit(train_poly, train_target)

LinearRegression()

In [23]:
### 훈련 및 테스트 정확도 확인하기
print("훈련 정확도 : ", lr.score(train_poly, train_target))
print("테스트 정확도 : ", lr.score(test_poly, test_target))

훈련 정확도 :  0.9898271546307027
테스트 정확도 :  0.9713771600629659


In [24]:
### 과대/과소 적합 확인하기
"""
(해석)
 - 훈련 및 테스트 정확도 확인 결과 과대 또는 과소적합이 일어나지 않는 일반화 모델로,
 - 선형, 다항회귀모델보다 높은 성능을 나타내기에
 - 특성 데이터를 이용해서 무게를 예측하는 모델로는 다중회귀모델을 사용하는 것이 좋을 것으로 판단됨
 - 이 모델을 사용하기 위해서는 길이, 높이, 두께 데이터를 이용하면 됩니다.
"""

'\n(해석)\n - 훈련 및 테스트 정확도 확인 결과 과대 또는 과소적합이 일어나지 않는 일반화 모델로,\n - 선형, 다항회귀모델보다 높은 성능을 나타내기에\n - 특성 데이터를 이용해서 무게를 예측하는 모델로는 다중회귀모델을 사용하는 것이 좋을 것으로 판단됨\n - 이 모델을 사용하기 위해서는 길이, 높이, 두께 데이터를 이용하면 됩니다.\n'

In [30]:
### test데이터로 예측을 수행한 후
# - 예측결과를 이용해서 절대값에 의한 평균오차 확인하기
from sklearn.metrics import mean_absolute_error

test_pred = lr.predict(test_poly)
print("절대값에 의한 평균오차 : ", mean_absolute_error(test_target, test_pred))

절대값에 의한 평균오차 :  30.2168895903429
